ex01 : ex01.c ../../engine/button.c ../../engine/util.c
	gcc -o $@ $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf
ex02 : ex02.c ../../engine/button.c ../../engine/util.c
	gcc -o $@ $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf
ex03 : ex03.c  ../../engine/util.c ../../engine/button.c ../../engine/text_lable.c
	gcc -o $@ $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_ttf 