 ex01 : ex01.c 
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
 ex02 : ex02.c 
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
 ex03 : ex03.c 
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
 ex04 : ex04.c 
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2 -lSDL2_image
 ex05 : ex05.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex06 : ex06.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex07 : ex07.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex08 : ex08.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex09 : ex09.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex10 : ex10.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex11 : ex11.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex12 : ex12.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex13 : ex13.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex14 : ex14.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
ex15 : ex15.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
report1 : report1.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
report2 : report2.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
pt1 : pt1.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
pt2 : pt2.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2
pt3 : pt3.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2main -lSDL2