pt1 : pt1.c
	gcc -o $@.exe $^
pt2 : pt2.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt3 : pt3.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt4 : pt4.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt5 : pt5.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt6 : pt6.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt7 : pt7.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt8 : pt8.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt9 : pt9.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt10 : pt10.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt11 : pt11.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt12 : pt12.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt13 : pt13.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt14 : pt14.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image
pt15 : pt15.c
	gcc -o $@.exe $^ -lmingw32 -lSDL2_main -lSDL2 -lSDL2image